name: Council Request
description: Request for a council to be added to the repository
labels: ["council request"]

body:
    - type: input
      id: council
      attributes:
          label: Name of Council
          description: What council are you wishing to be added
          placeholder: e.g. Huntingdon District Council
      validations:
          required: true
    - type: input
      id: postcode
      attributes:
          label: Example Address/Postcode
          description: Please provide a tested working example address/postcode for the council's area
          placeholder: e.g. PE7 3YQ
      validations:
          required: true
    - type: textarea
      id: extra
      attributes:
          label: Additional Information
          description: Add any other information here
          placeholder: Links to the councils site, information you have already gathered
    - type: checkboxes
      id: verification
      attributes:
        label: Verification
        description: 'Please verify that you''ve followed these steps:'
        options:
          - label: I''ve checked the [wiki](https://github.com/robbrad/UKBinCollectionData/wiki/Councils#contents) and verified that my council has not been added
            required: true
          - label: I''ve checked that a request for my council does not already exist in the [Issues tracker](https://github.com/robbrad/UKBinCollectionData/issues?q=is%3Aopen+is%3Aissue+label%3A"council+request")
            required: true
          - label: I have provided a tested working address/postcode/UPRN with bin collections available, as well as a link to the council''s website
            required: true
          - label: I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script
            required: true
